import { CommonProvider } from "@/context/commonContext";
import "./globals.css";
import "@/public/scss/index.scss";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CommonProvider>{children}</CommonProvider>
      </body>
    </html>
  );
}
